
export const MENU_GET_REQUESTED = "MENU_GET_REQUESTED";
export const MENU_GET_SUCCESS = "MENU_GET_SUCCESS";
export const MENU_GET_FAILED = "MENU_GET_FAILED";
export const MENU_INFO = "MENU_INFO";
export const USER_LOGOUT_REQUESTED = "USER_LOGOUT_REQUESTED";

