
export const PROFILES_GET_REQUESTED = "PROFILES_GET_REQUESTED";
export const PROFILES_GET_SUCCESS = "PROFILES_GET_SUCCESS";
export const PROFILES_GET_FAILED = "PROFILES_GET_FAILED";
export const PROFILES_INFO = "PROFILES_INFO";
export const USER_LOGOUT_REQUESTED = "USER_LOGOUT_REQUESTED";

