
export const USER_LOGIN_REQUESTED = "USER_LOGIN_REQUESTED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGOUT_REQUESTED = "USER_LOGOUT_REQUESTED";
export const USER_LOGIN_INFO = "USER_LOGIN_INFO";
